apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    app: worker-service
spec:
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    app: worker-service
