apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    app: auth-service
